version: "3"
services:
  jupyter:
    build: .
    volumes:
      - $PWD:/tmp/working
    working_dir: /tmp/working
    ports:
      - "8080:8080"
    hostname: localhost
    # for GPU
    # runtime: nvidia
